# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /post/:title

# Setup
title:            "huangxiaopeng"
description:      "Tyler Benziger writes about things"
url:              http://tybenz.com
baseurl:          "/"
paginate:         10

author:
  name:           "Huang XiaoPeng"

# Custom vars
twitter:        https://twitter.com/tybenz
github:         https://github.com/tybenz
