# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown

title: 黄晓棚的Github
description: 分享各种技术偏方
disqus: xiaoxiaosang
author:
  name: huangxiaopeng
  email: 397110686@qq.com
  github: xpi	
  twitter: none
  pinterest: none
  linkedin: none
  bio: xiaoxiaosang,huang xiaoxiaosang
  email_md5: 95DC3AFB27F2AB9E4B9035E6FBBA51F6

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://xpi.github.io/blog/
