# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /post/:title

# Setup
title:            "黄晓棚的Github"
description:      "总想记录一些什么"
url:              http://xpi.github.com
baseurl:          "/"
paginate:         10

author:
  name:           "Huang XiaoPeng"

# Custom vars
twitter:        https://twitter.com/huangxiaopeng
github:         https://github.com/xpi
